name: Run cargo test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Rustc version
      run: |
        rustup update
        rustup toolchain install 1.80.0
        rustup default 1.80.0

    - name: Run cargo test
      run: |
        cd virdant
        cargo test
